
language: node_js
node_js:
  - "4.1"

branches:
  only:
    - master

before_install:
  - npm install -g eslint
  - npm install gulp -g

script:
  - npm install
  - gulp test 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

notifications:
  email:
    - john.patterson@secondphase.com.au